### ISSUE TITLE
[cga] Centralize compilation flags

### ISSUE THREAD

**Issue by mimaric** [clara-parabricks/GenomeWorks#291]
Currently every module defines its own compilation flags. In some cases this is the wanted behavior, but in others (C++ standard, warning level..) it causes confusion.

Think about which flags should be set for the whole SDK.

**Comment by ahehn-nv** [comment]
Not a cmake expert, but I think the cleanest way would be to define a central interface library `add_library(cga_common INTERFACE)`, set the properties there via `target_compile_options(cga_common INTERFACE <flags>)` & friends, and then link all our actual targets against this interface library. There was a nice talk by Robert Maynard on Modern CMake + CUDA at last year's GTC https://developer.nvidia.com/gtc/2019/video/S9444.
