### ISSUE TITLE
document missing

### ISSUE THREAD

**Issue by cschin** [clara-parabricks/GenomeWorks#33]
I get GitHub 404 for this link 
https://github.com/clara-genomics/ClaraGenomicsAnalysis/blob/master/docs/annotated.html
from this page 
https://github.com/clara-genomics/ClaraGenomicsAnalysis/blob/master/docs/README-SDK.md

I guess the generated HTML is not checked in?

**Comment by tijyojwad** [comment]
@cschin Indeed, they're not checked in. This README slipped through unfortunately. The best way to get docs would be to generate them as described in https://github.com/clara-genomics/ClaraGenomicsAnalysis/blob/master/README.md#enable-doc-generation

We'll take a look at checking the documentation in as well so it's ready for use

**Comment by tijyojwad** [comment]
Pushed #34 to make the setup less confusing. No more README in the `docs` folder. API documentation still not checked in though, but will add it to our feature list

**Comment by tijyojwad** [comment]
Closing as docs have been available in https://clara-parabricks.github.io/GenomeWorks/
