### ISSUE TITLE
[cudamapper] example API usage

### ISSUE THREAD

**Issue by armintoepfer** [clara-parabricks/GenomeWorks#340]
Hi!

I really appreciated the example API usage for cudapoa and would like to ask for something similar for cudamapper.

Thanks!
Armin

**Comment by vellamike** [comment]
Hi @armintoepfer  thanks for the feedback. This is something we will prioritise.

**Comment by armintoepfer** [comment]
Any update on this? I really would like to get started.

**Comment by vellamike** [comment]
Hi @armintoepfer - apologies for the delay on this request. We are working on it and will let you know as soon as we publish a sample.

**Comment by armintoepfer** [comment]
Keep me posted.

**Comment by mimaric** [comment]
Reassigning this to @nvvishanthi
