### ISSUE TITLE
performance drop-down related to CUDA_NVCC_FLAGS

### ISSUE THREAD

**Issue by r-mafi** [clara-parabricks/GenomeWorks#341]
cudapoa_benchmark seems to be ~10% slower which this line is added to `cmake/CUDA.cmake`:
`set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} ${ARCH_FLAGS}")`   ([link here](https://github.com/r-mafi/ClaraGenomicsAnalysis/commit/2b5d632fa66f5471b7ac3c27106af721bf4530a1#diff-d77f46a67237a37b9c4eae17e6a1b741R27))

![image](https://user-images.githubusercontent.com/59714522/77860190-c8459000-71db-11ea-919d-fe9b20d54557.png)

**Comment by ahehn-nv** [comment]
So cudapoa got slower with this line? That is unexpected...
Could you recompile with `make VERBOSE=1` and share the respective NVCC command lines that make/cmake uses to compile the CUDA code?

**Comment by r-mafi** [comment]
> Could you recompile with `make VERBOSE=1` and share the respective NVCC command lines that make/cmake uses to compile the CUDA code?

yes, looks unexpected. make in verbose mode did not output any meaningful info, but here is what I get with cmake on my workstation (it has Titan V and GeForce GT 710):
```
-- Using CUDA 10.2 from /usr/local/cuda-10.2
-- Autodetected CUDA architecture(s):  7.0 3.5
-- NVCC arch flags - -gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_35,code=sm_35
```
 I expect the issue be reproducible on other systems as well, we need to call cmake with benchmarks enabled:
`cmake .. -DCMAKE_BUILD_TYPE=Relesase -DCMAKE_INSTALL_PREFIX=install -Dcga_cuda_gen_all_arch=OFF -Dcga_enable_benchmarks=ON`
 Then running `/cudapoa/benhmarks/benchmark_cudapoa` with/without that line in `CUDA.cmake` results in ~10% difference.

**Comment by r-mafi** [comment]
I also added a line to output `CUDA_NVCC_FLGAS` in addition to `ARCH_FLAGS`, this is what I got:
```
-- NVCC arch flags - -gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_35,code=sm_35
-- CUDA NVCC flags -  -lineinfo -use_fast_math -Xcompiler -Wall,-Wno-pedantic
```

**Comment by ahehn-nv** [comment]
If I do
```
make clean
make VERBOSE=1 cudapoa
```
I get output like
```
-- Generating [...]/cudapoa/CMakeFiles/cudapoa.dir/src/./cudapoa_generated_cudapoa_kernels.cu.o  
/opt/cuda-10.2/bin/nvcc [...]/cudapoa/src/cudapoa_kernels.cu -c -o [...] -ccbin /usr/bin/cc -m64 -Xcompiler ,\"-fopenmp\",\"-O3\",\"-DNDEBUG\" -lineinfo -use_fast_math -Xcompiler -Wall,-Wno-pedantic -gencode arch=compute_30,code=sm_30 [...]
```
Could you try that again? Would be helpful what flags nvcc actually gets in the end. I do not understand cmake well enough to be certain of my predictions what cmake will give to it given the variables.

**Comment by r-mafi** [comment]
not sure why I can't get `-gencode arch` in verbose.
```
-- Generating [...]/cudapoa/CMakeFiles/cudapoa.dir/src/./cudapoa_generated_cudapoa_kernels.cu.o
/usr/local/cuda-10.2/bin/nvcc [...]/cudapoa/src/cudapoa_kernels.cu -c -o [...] -ccbin /usr/bin/cc -m64 -Xcompiler ,\"-fopenmp\" -lineinfo -use_fast_math -Xcompiler -Wall,-Wno-pedantic -std=c++11 -DNVCC
```

**Comment by ahehn-nv** [comment]
Hm, strange.... Have you tried building from scratch in a new build directory?

**Comment by r-mafi** [comment]
yes, I just downloaded a fresh copy from git and tested on that. Have you tried to see if it is reproducible on your machine?

**Comment by r-mafi** [comment]
The changes caused by [this merge ](https://github.com/r-mafi/ClaraGenomicsAnalysis/commit/2b5d632fa66f5471b7ac3c27106af721bf4530a1), shown by red cross:
![image](https://user-images.githubusercontent.com/59714522/77946836-f933cc80-7290-11ea-9853-91d81b19d5e2.png)
is not limited to performance. cudaPOA code is producing wrong results as well:
 If in the long read sample we create 2 identical long reads of length 10k, the output POA graph is expected to have 10k nodes and 9999 edges. This works fine right before the merge, after that it creates a graph with 11593 nodes and 13378 edges.

note: removing `set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} ${ARCH_FLAGS}")`
 , although had an impact on performance, but still generated the wrong graph.

**Comment by r-mafi** [comment]
results on prom: top with the line and bottom without the line
![image](https://user-images.githubusercontent.com/59714522/77959853-4ae65200-72a5-11ea-8861-34bf5d400ea8.png)

**Comment by r-mafi** [comment]
testing with cuobjdump as per Andreas' suggestion, it can be verified the faster code uses `arch = sm_30,` and slower one uses `arch = sm_70`

**Comment by atadkase** [comment]
Similar regression is observed for cudaaligner as well. Creating a WAR PR to revert the arch choice change and filing a bug internally for tracking.

**Comment by ahehn-nv** [comment]
Good to know that cudaaligner is also affected... Thanks @atadkase!

**Comment by atadkase** [comment]
Confirmed that regression was introduced by new instructions in later architectures. It cannot be addressed currently, but it might be fixed in the future. Closing this as WNF as a WAR has been merged in already, and it does not affect multi-batch cases.
