### ISSUE TITLE
[sdk] add CI for CUDA 11 and validate support

### ISSUE THREAD

**Issue by tijyojwad** [clara-parabricks/GenomeWorks#460]
Add a CUDA 11 Ubuntu 18.04 test to gpuCI for GenomeWorks

**Comment by tijyojwad** [comment]
Once support is validated, update README to notify users of CUDA 11 support.

**Comment by ohadmo** [comment]
@tijyojwad should we also add support to CUDA 10.2 ?

**Comment by tijyojwad** [comment]
Consider adding Ubuntu 20.04 as part of this test instead of 18.04

@ohadmo - yes we can add 10.2 once we remove the 9.x tests

**Comment by ohadmo** [comment]
@tijyojwad https://hub.docker.com/r/gpuci/rapidsai-base & https://hub.docker.com/r/gpuci/rapidsai-base-driver are deprecated, CUDA 11 was not added to them. need to change our env repository https://github.com/clara-parabricks/gpuci-build-environment + https://github.com/clara-parabricks/gpuci-build-environment-dnabricks to use:
- https://hub.docker.com/r/gpuci/rapidsai.
- https://hub.docker.com/r/gpuci/rapidsai-driver

**Comment by tijyojwad** [comment]
Let's also look at what it would take to add gcc-9 to GenomeWorks CI

**Comment by ahehn-nv** [comment]
gcc 9 is the default compiler on ubuntu-20.04.

**Comment by ahehn-nv** [comment]
Can't we use https://hub.docker.com/r/nvidia/cuda? There are ubuntu20.04 containers with CUDA 11.

**Comment by tijyojwad** [comment]
@ahehn-nv the gpuCI images have some more restrictions because they need several additional packages. We typically depend on the core gpuCI images and then add our own packages on top - so we just need to check with them if they have a CUDA 11 Ubuntu 20.04 base image we can use (and if not, ask them to add one).

**Comment by o8191** [comment]
@ahehn-nv @tijyojwad, this is possible to add the CUDA 11, support, however, this requires to add an additional  `miniconda-cuda` image to https://hub.docker.com/r/gpuci/miniconda-cuda/tags?page=1 which supports Ubuntu 20. Once I push the new env docker files.
