### ISSUE TITLE
Permission denied (publickey). fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by SuchismitaSahu1993** [clara-parabricks/GenomeWorks#470]
Error on executing the following command:
$ git clone --recursive git@github.com:clara-genomics/ClaraGenomicsAnalysis.git
Cloning into 'ClaraGenomicsAnalysis'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Kindly recommend solution.
Thanks!

**Comment by r-mafi** [comment]
did you try cloning with HTTPS?
$ git clone --recursive https://github.com/clara-parabricks/GenomeWorks.git

**Comment by SuchismitaSahu1993** [comment]
Cloning with HTTPS worked. Thanks!

**Comment by vellamike** [comment]
Maybe we should change the documentation to use https to avoid this confusion??

**Comment by tijyojwad** [comment]
Yeah definitely - https://github.com/clara-parabricks/GenomeWorks/pull/421/files has this fix from @edawson and had been sitting for some time. Just updated the branch, should be merged soon.
