### ISSUE TITLE
[sdk] Update the way we fetch CUB

### ISSUE THREAD

**Issue by mimaric** [clara-parabricks/GenomeWorks#570]
CUDA 11 ships with CUB, so there is no need to download it separately into `3rdparty` (unless for some reason we need another version)

For pre-CUDA 11, CUB has been moved under Nvidia organization on GitHub: https://github.com/NVIDIA/cub/. Old link still works, but we should update it for consistency.

**Comment by mimaric** [comment]
FYI @tijyojwad @o8191

**Comment by ahehn-nv** [comment]
I submitted a PR a minute later :D https://github.com/clara-parabricks/GenomeWorks/pull/569
